### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by olafchou** [mheesakkers/sketch-image-replaste#1]
the picture in my desk , copy will not work。。。。。
![image](https://cloud.githubusercontent.com/assets/19890798/24136389/836ea866-0e49-11e7-9aa3-a7e622caa47d.png)

**Comment by mheesakkers** [comment]
Are you trying to copy from finder/desktop? For now this will not work. You can copy images in Sketch and replaste them or copy an image from the web and replace it.

**Comment by olafchou** [comment]
okay，thank you for your explaination

**Comment by olafchou** [comment]
but the sketch symbol doesn't work

**Comment by mheesakkers** [comment]
Images in Sketch symbols can be replaced with a clipboard image natively within Sketch. Select the symbol and on the right of the symbol panel click the image thumbnail and paste your copied image in there ;)

**Comment by mmic126** [comment]
why I cannot find your app via runner? please help!
