### ISSUE TITLE
Image not resizing in Sketch 47

### ISSUE THREAD

**Issue by jakelunde** [mheesakkers/sketch-image-replaste#4]
Using the image replaste plugin the image replaces the initial image, but does not resize to the same dimensions as the initial image.

**Comment by mheesakkers** [comment]
Hi, currently having some troubles with the plugin after the latest updates of Sketch. Plugin seems to be broken. Will look into it!

**Comment by jakelunde** [comment]
Thanks so much! Your plugin has helped my workflow SO MUCH. Great stuff!

**Comment by mheesakkers** [comment]
Plugin is working again. I will think about a resize feature, added to the todo!
